version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - .:/app
