version: "3.5"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: bash -c "go run main.go"
    volumes:
      - .:/go/src
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - TZ=$TZ
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - db_volumes:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d

volumes:
  db_volumes:
